### ISSUE TITLE
Hardcoded C-types in build script

### ISSUE THREAD

**Issue by Sympatron** [dzervas/platformio-arduino-rust#1]
First of all I think this is a really interesting project!

One thought I had about the build script: To support any target PlatformIO and Rust support, it is probably better to use Rust's `core::ffi::..` types instead of hard coding `int` as `i16` and so on, because these are platform dependent. And by the way I don't think `i16` is the correct type for `int` on a 32-bit platform anyway.

https://github.com/dzervas/platformio-arduino-rust/blob/0936d8521ddaf5e6c0870f8c7a57541410e9deff/cargo_build.py#L21-L42

**Comment by dzervas** [comment]
You're 99% right about the int.

Keep in mind tho that I don't see this project get anywhere, as the c++ code of Arduino is well... kinda bad... Globals are used like butter on bread and Rust is not into this weird shit. The boilerplate required for anything other than a blink is astonishing.

I'd tell you to check out the rust-embedded thing, which is amazingly structured and beutiful but currently I can't get BT to work and there's actually no USB stack available for nrf52840. I tried to write it. I didn't make it. I wasted many, many hours.

Right now the only solution to avoid writing C/C++ is circuitpython. Adafruit writes VERY nice and clean code - even its Arduino core is very nice.

If you get this to work, kudos, but I wouldn't waste any more energy on this shit if I were you

**Comment by Sympatron** [comment]
I didn't really plan on using it. I just found the idea interesting, found this problem and wanted to report it.
If you are so little into this project I would suggest adding a stronger disclaimer at the beginning of the readme to dissuade people from using this.
